### ISSUE TITLE
Does not work with JavaFX from JRE 9

### ISSUE THREAD

**Issue by bergmannf** [byteit101/JRubyFX-FXMLLoader#9]
It seems that Java 9 removed the `javafx.geometry.InsetsBuilder`, which is subclassed in `lib/fxmlloader/value_elts.rb`: [apidocs for javafx.geometry in JavaFX 8](https://docs.oracle.com/javase/8/javafx/api/javafx/geometry/package-summary.html)

When trying to run one of the examples from `JRubyFX` it fails, due to this.

Related to jruby/jrubyfx#119

**Comment by bolandross** [comment]
Having the same problem ...

**Comment by byteit101** [comment]
After digging into this problem, it appears jrubyfx-fxmloader will not be able to support java 9+ without significant work. https://github.com/jruby/jruby/issues/4165 is the easiest out as we can then avoid the problem entirely I think. 

The underlying issue is the new module system means we cannot access the com.sun clases we need to implement identical fxml parsing in ruby.

**Comment by byteit101** [comment]
JRubyFX 2.0 has been release, rendering this gem obsolete. If your issue still applies to JRubyFX 2.0, please reopen this issue on the JRubyFX issue tracker.
